### ISSUE TITLE
How to ignore destruction of object?

### ISSUE THREAD

**Issue by acki-m** [libnonius/nonius#12]
I want to ignore in the measurement the destruction of an object. I know the special objects:         `nonius::storage_for` & `nonius::destructable_object`

But I think it will not help me, I have following case:

```
MyObject obj = method_generate_myobject()
```

The method `method_generate_myobject()` will generate an instance of `MyObject` with automatica storage. The method has access to a private ctor which I cannot invoke directly.
How can I ignore with nonius the destruction of `MyObject` during the benchmark run?

**Comment by rmartinho** [comment]
I think there's just no way to do this. C++ simply won't let you disable RAII. I'll see if there's a loophole somewhere, but my gut feeling is that this is just fundamentally impossible due to the way the language is designed.

**Comment by rmartinho** [comment]
Wouldn't `NONIUS_BENCHMARK("x", []{ return method_generate_myobject(); })` do?

Internally, the framework binds the return value to a reference and takes a snapshot of the time before the scope ends, and therefore before the destructor runs. Basically, it uses temporary lifetime extension. Granted, all this relies on copy elision to work. I'll have to experiment a bit.

**Comment by acki-m** [comment]
In my version (official 1.0 release) there is no binding of the return value:
The following code will be executed:

```
void measure(Fun&& fun, std::false_type) {
            measure([&fun](int) { fun(); });
        }
```

When I run it with the debugger, it will clearly execute the dtor of the tmp object, before the measuring stops.
You need a way to fix this, this is very important. Otherwise this noise will ruin the measurement.

**Comment by rmartinho** [comment]
Ok, I'm curious about one thing: what would a hand-written benchmark for this look like? I can get an idea of how to make it work in nonius if I see a hand-written one.

**Comment by acki-m** [comment]
Ok, but where is the problem?

```
void benchmark()
{
    start_measure_time();
    MyObject obj = method_generate_myobject();
    finish_measure_time();
}
```

The creation of obj will be measured, but not the destruction process.
At the moment nonius works like this:

```
start_measure_time();
void benchmark()
{
    MyObject obj = method_generate_myobject();
}
finish_measure_time();
```

**Comment by rmartinho** [comment]
That's oversimplified. You need a loop so the code can be run several times. And you need to time the whole loop. That's a requirement to account for the clock's resolution. This is where I'm stuck. You can't stop and restart measurement every iteration because it introduces an unquantifiable amount of measurement error and that is a dealbreaker.

**Comment by acki-m** [comment]
Ahh sorry, then I am to little in the details of the benchmarking.Ok, but what about the mentioned: 

> binds the return value to a reference 

I didn't found this code in the current version. Is it there?

**Comment by rmartinho** [comment]
No, I misremembered from an older iteration of the design. Later on I changed it to the current design for unrelated reasons.

**Comment by rmartinho** [comment]
I've been thinking about this, and it's really hard to do it right if at all. One of nonius' goals is to provide trustworthy results, so I really cannot accept introducing measurement error that cannot be quantified. I'm closing as wontfix unless I come up with a viable way to do this.
