### ISSUE TITLE
Number of iterations is not determined using chronometer::measure() duration

### ISSUE THREAD

**Issue by ryb-ableton** [libnonius/nonius#27]
In the benchmarks below, `to_string(4.2) with sleep` always runs with 1 iteration, while `to_string(4.2) with no sleep` runs with around 100 iterations. This is because nonius::benchmark::prepare() computes the number of iterations based on the duration of the entire benchmark function, not the duration of the measure() function. This is a problem if the code prior to the measure() is expensive. In this example, the reported mean of the sleep version is 5.5 _micro_seconds, while the mean of the no-sleep version is 196 _nano_seconds!

```
#define NONIUS_RUNNER
#include <nonius.h++>
#include <thread>
#include <chrono>

NONIUS_BENCHMARK("to_string(4.2) with sleep", [] (nonius::chronometer chronometer) {
  std::this_thread::sleep_for(std::chrono::milliseconds(1));

  return chronometer.measure([] {
    return std::to_string(4.2);
  });
})

NONIUS_BENCHMARK("to_string(4.2) with no sleep", [] (nonius::chronometer chronometer) {
  return chronometer.measure([] {
    return std::to_string(4.2);
  });
})
```

**Comment by rmartinho** [comment]
Ah, good find. I'll write a test and fix this.
