### ISSUE TITLE
integrate with biicode

### ISSUE THREAD

**Issue by svark** [libnonius/nonius#28]
This would help other projects grab this tool easily into their testing projects as a dependency.

**Comment by rmartinho** [comment]
Unless someone brings a PR, I'm not going to try this before I'm sure biicode will stay alive (http://blog.biicode.com/biicode-just-the-company-post-mortem/)

**Comment by svark** [comment]
Hmm thats sad. Didn't know how that Biicode, the company is shutting. Biicode i still a great tool.
