### ISSUE TITLE
Websites not responding

### ISSUE THREAD

**Issue by bjoernpollex** [libnonius/nonius#44]
The websites http://nonius.io/ and http://flamingdangerzone.com/nonius are currently not loading for me. Everything else works fine.

**Comment by nabijaczleweli** [comment]
Update: [his server renewal failed after credit card stolen](http://chat.stackoverflow.com/transcript/message/28008444#28008444).

**Comment by sehe** [comment]
Both work for me. I also think https://rmf.io/ is preferrable (not sure)

**Comment by bjoernpollex** [comment]
Ok, both work now, closing this.
