### ISSUE TITLE
Highcharts license concerns

### ISSUE THREAD

**Issue by arximboldi** [libnonius/nonius#53]
Hi!

Sorry for being the legalist party pooper...

As part of my work for #36 I was looking at how the Highcharts to see how it works... When reading the code in the template distributed in Nonius, I does not say what license Highcharts has, it just claims that the license is at www.highcharts.com/license. When one visits that page, one is redirected to a shop to buy a proprietary license.

Somewhere hidden there is an option to buy get a non-commercial license, based on Creative Commons Non Commercial. By reading their FAQ: https://shop.highsoft.com/faq#Non-Commercial-0 it seems to me that the way Nonius uses it is not following their terms, or at least the way they interpret them. E.g.

> **Non-Commercial Redistribution**
> 
> You are allowed to distribute a Highsoft software product with non-commercial packages given that you fulfill two conditions:
> - Emphasize to your users that Highsoft software products are not free for commercial and Governmental use. You can do this on your download page or when your users activate a Highsoft Software Product in your application. 
> - Provide a link back to highcharts.com in the same location.
> 
> **May I use your Software under the Non-Commercial License for Open Source Projects?**
> 
> Although Highsoft´s Software have open source codes, our software is not licensed as an open source software and are unfortunately not compatible with any open source software license like Apache 2 or any GPL. See also Non-Commercial Redistribution

I think that the whole licensing of that library is a mess. It is impossible to know under what license was the library distributed when it was integrated in Nonius, and if those terms allowed rewording. Was this Non-Commercial clause added after-the-fact?

Since their licensing is messy, seems hostile to open-source and even unclear for commercial purposes (they make interpretations in the FAQ that are not sure are correct from understanding CC-NC), I suggest replacing this library altogether.  I don't have alternative suggestions for similar libraries, but I am going to look for them now and try to make a recommendation, and maybe implement it myself.

Cheers!

**Comment by arximboldi** [comment]
Ok, it didn't take long, here are some interesting alternatives:
- https://plot.ly/highcharts-alternative/
- http://nvd3.org/index.html
- http://visjs.org/index.html

Of those, `plotly.js` that seems better suited for our purposes as it includes controls for navigating the graph similar --and I'd say, better-- than those of Highcharts. I'm gonna proceed to try replace Highcharts with it.

**Comment by rmartinho** [comment]
I think it was NC at the time, but because it's not SA, I don't have to make nonius NC. I can't remember exactly why I picked this one over any alternatives at the time, but I agree that it should be replaced. I think at the time I only meant to use it for a while and then replace it but then didn't get to replacing it.

Their website does seem shadier now, as I clearly remember the non-paid option being prominent.
