### ISSUE TITLE
nonius.io does not load in Safari on OSX 10.12

### ISSUE THREAD

**Issue by d-xo** [libnonius/nonius#55]
When I go to https://nonius.io in safari on OSX 10.12 beta 3 the website fails to load with the error shown below:

![screen shot 2016-07-29 at 16 35 40](https://cloud.githubusercontent.com/assets/6689924/17251826/8d74d7b6-55aa-11e6-89aa-b83fa2667e27.png)

**Comment by nabijaczleweli** [comment]
norepro

**Comment by rmartinho** [comment]
I had to update the set of ciphers allowed by the server. It's working now.
