### ISSUE TITLE
undefined reference to `main'

### ISSUE THREAD

**Issue by ghost** [libnonius/nonius#66]
Hey,

I've tried to compile the examples but I'm getting `undefined reference to main`
git log shows : 78df23a7ed94a7311dfa10db531fe2a4c810f479

```
g++ -o example2 example2.c++ --std=c++14 -I/home/rsoeldner/custom/nonius/include -I/home/rsoeldner/custom/nonius/include/nonius -lpthread
/usr/lib/../lib64/crt1.o: In function `_start':
/home/abuild/rpmbuild/BUILD/glibc-2.19/csu/../sysdeps/x86_64/start.S:118: undefined reference to `main'
collect2: error: ld returned 1 exit status


```

**Comment by ghost** [comment]
The problem is fixed with`include <nonius_single.h++>`

**Comment by rmartinho** [comment]
No, it's not. This is fixed by using a nonius [release](https://github.com/rmartinho/nonius/releases), as documented in the second paragraph of the [documentation](https://nonius.io), or by performing a build, which will be documented for contributors in the next release.

**Comment by rmartinho** [comment]
See #21
