### ISSUE TITLE
Site is not working

### ISSUE THREAD

**Issue by bernex** [libnonius/nonius#93]

**Comment by bjoernpollex** [comment]
The website https://nonius.io is not working, FireFox reports this:

```
nonius.io uses an invalid security certificate. 

The certificate is not trusted because it is self-signed. 
The certificate is not valid for the name nonius.io. 

Error code: SEC_ERROR_UNKNOWN_ISSUER
```

It's not even possible to add a security exception:

> This site uses HTTP Strict Transport Security (HSTS) to specify that Firefox may only connect to it securely. As a result, it is not possible to add an exception for this certificate.

**Comment by lnicola** [comment]
I'm able to add a security exception, but I get a HTTP Basic Authentication prompt for `rutorrent` (BitTorrent client).
