### ISSUE TITLE
nonius.h++ should include main.h++

### ISSUE THREAD

**Issue by shikharbhardwaj** [libnonius/nonius#99]
```
#define NONIUS_RUNNER
#include <nonius/nonius.h++>
```
generates `undefined reference to main`.

```
#define NONIUS_RUNNER
#include <nonius/nonius.h++>
#include <nonius/main.h++>
```
Works.

Is this a change not documented in the guides?

Examples don't compile without this change.

**Comment by rmartinho** [comment]
Please grab a release from the releases page: https://github.com/rmartinho/nonius/releases. This is mentioned in the second paragraph of the documentation.
